### ISSUE TITLE
Risingos 3.1 not working

### ISSUE THREAD

**Issue by 13didounet** [ItsLynix/RisingTreble#1]
niHello
Rising 3.1 not working
Lenovo p11 plus
mediatek chip
kernel 4.14.186

Ref ponces commented 3 days ago
Tell your GSI devs to be updated on TD patches which fix this, namely the latest one.
https://github.com/TrebleDroid/treble_experimentations/releases/download/ci-20240508/patches-for-developers.zip

Based on android-14.0.0_r37
Sync with latest sources of TrebleDroid
Support kernels <= 4.14

Project SAKURA  based on Lineage OS start
https://github.com/ChonDoit/treble_sakura_patches/releases

**Comment by melontini** [comment]
I can confirm that the latest build is not booting on the Realme 8 pro (Kernel 4.14).

The crash is identical to https://github.com/TrebleDroid/treble_experimentations/issues/117, but wrapped in an InvocationTargetException because... Java.

I assume you need this patch https://github.com/TrebleDroid/platform_packages_modules_Connectivity/commit/e47def17699ce64f2ebf0f7a928f3f91ff0cd7f4, as latest Lineage by AndyYan boots and connects to VPNs just fine. ([Link](https://github.com/AndyCGYan/lineage_patches_unified/blob/3963eaa06e0a6b717e77625d27f070dbad1f161d/patches_treble_td/platform_packages_modules_Connectivity/0006-Fixup-Support-non-working-BPF-maps-on-old-BPF-less-k.patch))

**Comment by ItsLynix** [comment]
Thank you for sharing, it does seem like we're missing that patch, I'll look into it.

**Comment by melontini** [comment]
It looks like it was originally made for lineage and is not yet in the TD patchset. Anyways, thanks for looking into it.

**Comment by ItsLynix** [comment]
Please check the newly released hotfix builds, reopen if it isn't fixed.

**Comment by melontini** [comment]
Yes, everything boots now, thank you.

**Comment by 13didounet** [comment]
My tablet also starts.
Thanks for everything
